### ISSUE TITLE
Error while enabling mcMMO-WorldGuard

### ISSUE THREAD

**Issue by 9190281** [mcMMO-Dev/mcMMO-WorldGuard#7]
Hello,
I have tried to loadup mcMMO-WorldGuard on my server and it throws me an error.

mcMMO version: #45 (drtshock's jenkins server)
mcMMO-WorldGuard version: v1.0.2

Error: http://pastebin.com/DzwQSiJ0

**Comment by TfT-02** [comment]
It's an harmless error which occurs when mcMMO-WorldGuard is unable to determine mcMMO's version. This was caused because we accidentally tagged our mcMMO builds with 'dev' instead of 'SNAPSHOT'
https://github.com/mcMMO-Dev/mcMMO/commit/ecfdd75e360b8d281c6060773527066db0fe4349

**Comment by TfT-02** [comment]
Erm, I said it's harmless, but didn't realize that mcMMO-WorldGuard disables itself when it's not sure which mcMMO version the server is running. You will have to update mcMMO to the latest dev build in order to get mcMMO-WorldGuard to work. ;)
